import type { Category, Product, Order, CustomCakeOrder } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Tortlar', slug: 'tortlar', isActive: true },
  { id: 'cat-2', name: 'Pirojniylar', slug: 'pirojniylar', isActive: true },
  { id: 'cat-3', name: 'Art Desertlar', slug: 'art-desertlar', isActive: true },
  { id: 'cat-4', name: 'Korpus Pirojniylar', slug: 'korpus-pirojniylar', isActive: true },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Pistachio & Raspberry Royal Cake',
    description: 'Tabiiy pista kremi, yangi moroq malinasi va 24K yeyiladigan oltin barglari bilan bezatilgan eksklyuziv biskvitli tort.',
    ingredients: 'Eron pistasi, malina pyuresi, Mascarpone pishlogʻi, sariyogʻ, tabiiy vanil extract',
    price: 280000,
    imageUrl: '/products/pistachio_berry_cake.jpg',
    isAvailable: true,
    categoryId: 'cat-1',
    portion: '8-10 kishilik',
    weightGrams: 1500,
    calories: 340,
  },
  {
    id: 'prod-2',
    name: 'Belgian Dark Chocolate Mousse Cake',
    description: '70% Belgiya shokoladi va findiq pralinasi aralashmasidan tayyorlangan oliy navli shokoladli tort.',
    ingredients: 'Belgiya qora shokoladi, findiq pralinasi, qaymoq, kakao biskvit',
    price: 260000,
    imageUrl: '/products/chocolate_truffle_cake.jpg',
    isAvailable: true,
    categoryId: 'cat-1',
    portion: '6-8 kishilik',
    weightGrams: 1300,
    calories: 390,
  },
  {
    id: 'prod-3',
    name: 'Ruby Velvet Heart Korpus Pirojniy',
    description: 'Yurak shaklidagi yaltiroq korpusli mus desert. Ichida qulupnayli konfi va nordon krem-chiz.',
    ingredients: 'Oq shokolad korpus, qulupnayli konfi, krem-chiz mus, vanil',
    price: 45000,
    imageUrl: '/products/red_velvet_art.jpg',
    isAvailable: true,
    categoryId: 'cat-4',
    portion: '1 dona',
    weightGrams: 160,
    calories: 280,
  },
  {
    id: 'prod-4',
    name: 'Artisan French Macaron Box (12 dona)',
    description: 'Fransuz retsepti boʻyicha tayyorlangan Bodom unli rang-barang makaronlar toʻplami.',
    ingredients: 'Bodom uni, lavanda, shoʻr karamel, pista va malina filling',
    price: 180000,
    imageUrl: '/products/pistachio_berry_cake.jpg',
    isAvailable: true,
    categoryId: 'cat-3',
    portion: '12 dona box',
    weightGrams: 300,
    calories: 420,
  },
  {
    id: 'prod-5',
    name: 'Strawberry Choux Pastry Set (4 dona)',
    description: 'Qirchillama shu pirojniylari, ichida diplomat kremi va yangi qulupnay boʻlaklari.',
    ingredients: 'Sho pishiriq xamiri, diplomat krem, Yangi qulupnay, shakar pudrasi',
    price: 85000,
    imageUrl: '/products/red_velvet_art.jpg',
    isAvailable: true,
    categoryId: 'cat-2',
    portion: '4 dona set',
    weightGrams: 360,
    calories: 310,
  },
  {
    id: 'prod-6',
    name: 'Mango & Passionfruit Sphere',
    description: 'Tropik mango va marakuya musidan tayyorlangan mevali korpus deserti.',
    ingredients: 'Mango pyuresi, marakuya konfi, oq shokolad shell, biskvit crumble',
    price: 52000,
    imageUrl: '/products/chocolate_truffle_cake.jpg',
    isAvailable: true,
    categoryId: 'cat-4',
    portion: '1 dona',
    weightGrams: 175,
    calories: 250,
  },
  {
    id: 'prod-7',
    name: 'Royal Eclair Gold Box (6 dona)',
    description: 'Qora shokolad glaze va oltin changi bilan bezatilgan klassik Fransuz eklerlari.',
    ingredients: 'Ekler xamiri, shokoladli ganash, oltin zarra',
    price: 120000,
    imageUrl: '/products/chocolate_truffle_cake.jpg',
    isAvailable: false,
    categoryId: 'cat-2',
    portion: '6 dona box',
    weightGrams: 420,
    calories: 330,
  },
  {
    id: 'prod-8',
    name: 'San Sebastian Basque Cheesecake',
    description: 'Ustki qismi tutatilgan, ichi yumshoq kremsimon klassik Bask pishlogʻi torti.',
    ingredients: 'Filadelfiya krem-chiz, qaymoq, tuxum, mevali sous',
    price: 220000,
    imageUrl: '/products/pistachio_berry_cake.jpg',
    isAvailable: true,
    categoryId: 'cat-1',
    portion: '8 kishilik',
    weightGrams: 1400,
    calories: 360,
  },
];

export const MOCK_INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 1001,
    status: 'PREPARING',
    deliveryType: 'DELIVERY',
    deliveryAddress: "Toshkent shahri, Yunusobod tumani, Amir Temur ko'chasi 42",
    paymentMode: 'CARD_TRANSFER',
    paymentStatus: 'PAID',
    totalAmount: 325000,
    phone: '+998 99 495 78 06',
    notes: 'Tugʻilgan kun uchun tabriknoma kartochkasi qoʻshing iltimos.',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    items: [
      { id: 'item-1', productName: 'Pistachio & Raspberry Royal Cake', price: 280000, quantity: 1 },
      { id: 'item-2', productName: 'Ruby Velvet Heart Korpus Pirojniy', price: 45000, quantity: 1 }
    ]
  }
];

export const MOCK_CUSTOM_CAKES: CustomCakeOrder[] = [
  {
    id: 'cust-501',
    requestNumber: 501,
    description: 'Ikki qavatli toʻy torti, pushti va oltin gullar bilan bezatilgan. Pista va malina magʻzi.',
    referenceImages: ['/products/pistachio_berry_cake.jpg'],
    phone: '+998 91 023 15 24',
    deliveryType: 'DELIVERY',
    deliveryAddress: 'Mirzo Ulugʻbek tumani, Mustaqillik shoh koʻchasi 15',
    status: 'PRICE_OFFERED',
    estimatedPrice: 750000,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  }
];
